In [1]:
import numpy as np

In [2]:
# we can create a array of n-dimen of zeros using this built in function
a= np.zeros((2,3,3))

In [3]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [4]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
#b=np.full_like(a, 23, dtype='int32')
b=np.full(a.shape, 23, dtype='int32')
b

array([[[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]],

       [[23, 23, 23],
        [23, 23, 23],
        [23, 23, 23]]], dtype=int32)