In [14]:
import numpy as np

In [15]:
# initialise a array using numpy int16 is smaller which takes less space
a = np.array([1,2,3,4], dtype='int32')
print(a)

[1 2 3 4]


In [16]:
#creating n-Dimen array
b = np.array([[5,7,8],[1,2,4]])
print(b)

[[5 7 8]
 [1 2 4]]


In [ ]:
# to get a pecific element we can use default indexing starting from zero

b[0,2]

np.int64(8)

In [17]:
# get dimention with .ndim
print(f"a is : {a.ndim}")
print(f"b is : {b.ndim}")

a is : 1
b is : 2


In [18]:
#get shape, its a vector
print(a.shape)
print(b.shape)


(4,)
(2, 3)


In [19]:
# get type
a.dtype

dtype('int32')

In [20]:
#get size, here we can choose the dtype using dtype keyword while taking array input

print(b.itemsize) # as b is a n-dimen array the size will increase 
print(a.itemsize)


8
4


In [27]:
b[0, :]

array([5, 7, 8])

In [29]:
b[:,1]

array([7, 2])

In [30]:
arr=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [36]:
arr

array([[ 1,  2,  3, 19,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [35]:
arr[0, 1:6:2]

array([ 2, 19,  6])

In [34]:
arr[0,3]=19

In [40]:
arr_two = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [41]:
arr_two

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# to get specific elements we need to check from outside in indexing applies here as well

arr_two[1, 0,1]

np.int64(6)